name: Build

on: [push, pull_request]

jobs:
  build:
    name: Build on Ubuntu
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1

    - name: Fetch dependencies
      run: go get -d ./...

    - name: Build
      run: go build

  nix-build:
    name: nix-build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1

    - name: Install Nix
      run: |
        curl -L https://nixos.org/nix/install | sh
        . ~/.nix-profile/etc/profile.d/nix.sh
        # Use latest stable nixpkgs channel
        nix-channel --add https://nixos.org/channels/nixos-20.03 nixpkgs
        nix-channel --update

    - name: Build
      run: |
        . ~/.nix-profile/etc/profile.d/nix.sh
        nix-build
